before_install:
  - sudo apt-get install libicu-dev
language: node_js
node_js:
  - 0.9
  - 0.8
  - 0.6
notifications:
  webhooks: 
    urls:
      - http://webhooks.nodejitsu.com/1/deploy
    on_success: always
    on_failure: never
